{{- if and .Values.prometheusRule.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.prometheusRule.rules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "cell0.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.prometheusRule.namespace }}
  labels:
    {{- include "cell0.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    {{- with .Values.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.prometheusRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
    - name: {{ include "cell0.fullname" . }}
      rules:
        {{- toYaml .Values.prometheusRule.rules | nindent 8 }}
{{- end }}
