# Cell 0 OS Kubernetes Manifests
# Kustomization for deploying all manifests

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cell0

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secrets.yaml
  - 03-deployment.yaml
  - 04-service.yaml
  - 05-ingress.yaml
  - 06-networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: cell0-os

images:
  - name: ghcr.io/yigremtamiru/cell0-os
    newTag: main
