apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cell0
  namespace: cell0
  labels:
    app.kubernetes.io/name: cell0
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cell0
