apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cell0
  namespace: cell0
  labels:
    app.kubernetes.io/name: cell0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cell0
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
