apiVersion: v1
kind: Service
metadata:
  name: cell0
  namespace: cell0
  labels:
    app.kubernetes.io/name: cell0
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 18800
      targetPort: http
      protocol: TCP
    - name: websocket
      port: 18801
      targetPort: websocket
      protocol: TCP
    - name: metrics
      port: 18802
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: cell0
